# Generated by Django 5.2.1 on 2025-05-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_rename_text_chatmessage_user_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='session_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='bot_reply',
            field=models.TextField(),
        ),
    ]
