# Generated by Django 5.2.1 on 2025-05-14 04:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_session_id_alter_chatmessage_bot_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
