# Generated by Django 5.2.1 on 2025-06-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_demo_url_project_download_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='requires_payment',
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('program', 'Program'), ('website', 'Website')], default='program', help_text="Defines if the project is a 'program' (downloadable/paid) or a 'website' (link).", max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, help_text="The live URL for 'website' type projects.", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='URL for a demo or preview of the project.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='download_url',
            field=models.URLField(blank=True, help_text='Public URL for free program downloads.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='file_path',
            field=models.CharField(blank=True, help_text='Internal path for protected program files.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price for paid programs/projects. Set to 0 for free.', max_digits=8),
        ),
    ]
